### ISSUE TITLE
Tests done in "repo-supervisor" are not detecting the Secrets 

### ISSUE THREAD

**Issue by arunics** [auth0/repo-supervisor#18]
After completing the Deployment and setting up the Webhook in my forked repo-supervisor repository. Test pull requests are not detecting and complete the check.
Wonder if there is an issue with my setup / webtask deployment. 

My PR  link : https://github.com/arunics/repo-supervisor-testing/pull/1

**Comment by radekk** [comment]
Hey @arunics,

I would suggest in the first step to check logs related to the Webtask platform. You're going to be able to verify if webhook really hits the desired location as well as check the logs if there is anything failing on the source code side.

Command for getting logs from the webtask:

```
#> wt logs
```

Also ensure that you have the Webtask client installed locally, otherwise you can grab logs from the web editor as well.

Let me know if you have any further questions. I'm closing this issue and please move the conversation to the Gitter chat - https://gitter.im/repo-supervisor/Lobby.
